### ISSUE TITLE
Renderlets redraw when sizing

### ISSUE THREAD

**Issue by ghost** [ruhley/dc.js#1]
Love the resizing/rescaling responsive graphs, however when you have a graph that includes lines drawn with the renderlet function, these lines will redraw each time you resize so finally you will have a graph full of lines

**Comment by ruhley** [comment]
Renderlets will always be triggered on render and redraw. You should probably use one of the other event listeners that are available - https://github.com/dc-js/dc.js/blob/master/web/docs/api-latest.md#dc.baseMixin+on

**Comment by gordonwoodhull** [comment]
Yes, or the renderlet should do a data join so that it only creates the line if it's not already there.

See these three lines of this example:

https://github.com/dc-js/dc.js/blob/develop/web/examples/bar-extra-line.html#L53-55

**Comment by ghost** [comment]
@gordonwoodhull i used the three lines you specified aswell, that still results in the same issue

**Comment by ghost** [comment]
how about using the prerender event trigger to delete any lines that are already there and then leaving the rest as is.

**Comment by gordonwoodhull** [comment]
Sure, there are lots of ways to solve it - you'd probably have to watch both prerender and preredraw events. 

You could also just have your renderlet delete all the lines and draw them again.

I was just trying to suggest a way that is elegant and does the minimal amount of work. But I admit it's a little delicate and I haven't been able to find an explanation of the trick, probably I learned it on the d3 user group.

(Basically the idea is to join against an array of size 1 so that if a thing is there it doesn't get added again, and then apply the attributes to either the old thing or the new thing.)

**Comment by ghost** [comment]
How would i do this. The array solution you suggested. Do you have an fiddle or some code or something

**Comment by gordonwoodhull** [comment]
I already pointed to a complete example!
